create database TESTE_3;
use TESTE_3;

DROP TABLE IF EXISTS Dados_cadastrais_Operadoras_Ativas;
DROP TABLE IF EXISTS Relatorio_cadop;

create table Relatorio_cadop(
    Registro_ANS INT NOT NULL PRIMARY KEY,
    CNPJ VARCHAR(14) UNIQUE,
    Razao_Social VARCHAR(255),
    Nome_Fantasia VARCHAR(255),
    Modalidade VARCHAR(255),
    Logradouro VARCHAR(255),
    Numero VARCHAR(255),
    Complemento VARCHAR(255),
    Bairro VARCHAR(255),
    Cidade VARCHAR(255),
    UF VARCHAR(2),
    CEP VARCHAR(10),
    DDD VARCHAR(3),
    Telefone VARCHAR(20),
    Fax VARCHAR(20),
    Endereco_eletronico VARCHAR(255),
    Representante VARCHAR(255),
    Cargo_Representante VARCHAR(255),
    Regiao_de_Comercializacao VARCHAR(255),
    Data_Registro_ANS DATE
);

create table Dados_cadastrais_Operadoras_Ativas (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REG_ANS INT NOT NULL,
    DATA_CADASTRO DATE,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15, 2),
    VL_SALDO_FINAL DECIMAL(15, 2)
);

LOAD DATA INFILE '/var/lib/mysql-files/Relatorio_cadop.csv'
INTO TABLE Relatorio_cadop
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(Registro_ANS, CNPJ, Razao_Social, Nome_Fantasia, Modalidade, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, DDD, Telefone, Fax, Endereco_eletronico, Representante, Cargo_Representante, Regiao_de_Comercializacao, Data_Registro_ANS);

LOAD DATA INFILE '/var/lib/mysql-files/1T2023.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');
    
LOAD DATA INFILE '/var/lib/mysql-files/2t2023.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');

LOAD DATA INFILE '/var/lib/mysql-files/3T2023.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');

LOAD DATA INFILE '/var/lib/mysql-files/4T2023.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = str_to_date(@DATA_CADASTRO,'%d/%m/%Y');

LOAD DATA INFILE '/var/lib/mysql-files/1T2024.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');

LOAD DATA INFILE '/var/lib/mysql-files/2T2024.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');

LOAD DATA INFILE '/var/lib/mysql-files/3T2024.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');

LOAD DATA INFILE '/var/lib/mysql-files/4T2024.csv'
INTO TABLE Dados_cadastrais_Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATA_CADASTRO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
    DATA_CADASTRO = REPLACE(@DATA_CADASTRO, '/', '-');


SELECT Razao_Social
FROM Relatorio_cadop
RIGHT JOIN Dados_cadastrais_Operadoras_Ativas 
ON Relatorio_cadop.Registro_ANS = Dados_cadastrais_Operadoras_Ativas.REG_ANS 
GROUP BY Registro_ANS
WHERE STRCMP(DESCRICAO, 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR ')
AND DATA_CADASTRO BETWEEN '2024-10-01' AND '2024-12-31'
OR DATA_CADASTRO BETWEEN '2023-10-01' AND '2023-12-31'
ORDER BY sum(VL_SALDO_INICIAL) - sum(VL_SALDO_FINAL) DESC
LIMIT 10;

SELECT REG_ANS, Razao_Social, sum(VL_SALDO_FINAL) - sum(VL_SALDO_INICIAL) as 'Saldo'
FROM Dados_cadastrais_Operadoras_Ativas
LEFT JOIN Relatorio_cadop
ON Dados_cadastrais_Operadoras_Ativas.REG_ANS = Relatorio_cadop.Registro_ANS
WHERE STRCMP(DESCRICAO, 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR ')
AND DATA_CADASTRO BETWEEN '2024-10-01' AND '2024-12-31'
OR DATA_CADASTRO BETWEEN '2023-10-01' AND '2023-12-31'
GROUP BY REG_ANS
ORDER BY sum(VL_SALDO_FINAL) - sum(VL_SALDO_INICIAL) DESC
LIMIT 10;

SELECT REG_ANS, Razao_Social, sum(VL_SALDO_FINAL) - sum(VL_SALDO_INICIAL) as 'Saldo'
FROM Dados_cadastrais_Operadoras_Ativas
LEFT JOIN Relatorio_cadop
ON Dados_cadastrais_Operadoras_Ativas.REG_ANS = Relatorio_cadop.Registro_ANS
WHERE DATA_CADASTRO BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY REG_ANS
ORDER BY sum(VL_SALDO_FINAL) - sum(VL_SALDO_INICIAL) DESC
LIMIT 10;